package net.one97.paytm.utils;

import com.alipay.mobile.nebula.resourcehandler.H5ResourceHandlerUtil;
import com.business.merchant_payments.deeplinkUtil.DeepLinkConstant;
import com.paytm.paymentsettings.merchantSubscriptions.view.ActiveSubscriptionActivity;
import com.paytm.utility.q;
import com.paytmmall.clpartifact.utils.CLPConstants;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import kotlin.g.b.k;
import net.one97.paytm.AJREmbedWebView;
import net.one97.paytm.AJROrderSummaryActivity;
import net.one97.paytm.AJRProfileActivity;
import net.one97.paytm.AJRSecuritySettings;
import net.one97.paytm.AJRWebViewActivity;
import net.one97.paytm.AJRYoutubeVideoPlay;
import net.one97.paytm.DeeplinkDeciderActivity;
import net.one97.paytm.activity.LoanLeadActivity;
import net.one97.paytm.auth.activity.AJRAuthActivity;
import net.one97.paytm.dynamic.module.movie.EventsModuleManager;
import net.one97.paytm.landingpage.activity.AJRMainActivity;
import net.one97.paytm.moneytransfer.view.activities.MoneyTransferLinkAccountActivity;
import net.one97.paytm.nativesdk.orflow.Utility;
import net.one97.paytm.recharge.common.activity.AJRRechargeUtilityActivity;
import net.one97.paytm.recharge.legacy.catalog.activity.AJRRechargeActivity;
import net.one97.paytm.recharge.presentation.activity.AJRAutomaticSubscriptionListActivity;
import net.one97.paytm.savedPaymentItem.AJRSavedPaymentActivity;
import net.one97.paytm.upgradeKyc.activity.AJRNonKYCDeeplink;
import net.one97.paytm.upgradeKyc.activity.MinKycPanAadharUpgradeActivity;
import net.one97.paytm.upi.awareness.view.UpiAwarenessActivity;
import net.one97.paytm.upi.passbook.view.UpiPassbookActivity;
import net.one97.paytm.upi.referral.UpiReferralActivity;
import net.one97.paytm.upi.registration.view.UpiLandingPageActivity;
import net.one97.paytm.upi.requestmoney.view.RequestMoneyV2Activity;
import net.one97.paytm.upi.util.UpiConstants;
import net.one97.paytm.wallet.activity.AJRQRActivity;
import net.one97.paytm.wallet.newdesign.activity.P2PActivity;
import net.one97.paytm.wallet.newdesign.activity.PaySendActivityV2;
import net.one97.paytm.wallet.newdesign.nearby.NearByMainActivity;
import net.one97.paytm.wallet.p2p.P2PReferShopActivity;

public final class b {

    /* renamed from: a  reason: collision with root package name */
    public static final b f69703a = new b();

    /* renamed from: b  reason: collision with root package name */
    private static final Map<String, String> f69704b;

    static {
        Map hashMap = new HashMap();
        String name = AJRMainActivity.class.getName();
        k.a((Object) name, "AJRMainActivity::class.java.name");
        hashMap.put(CLPConstants.GA_CHANNEL_NAME, name);
        String name2 = AJRRechargeActivity.class.getName();
        k.a((Object) name2, "AJRRechargeActivity::class.java.name");
        hashMap.put("mobile_prepaid", name2);
        String name3 = AJRRechargeActivity.class.getName();
        k.a((Object) name3, "AJRRechargeActivity::class.java.name");
        hashMap.put("mobile_postpaid", name3);
        String name4 = AJRRechargeActivity.class.getName();
        k.a((Object) name4, "AJRRechargeActivity::class.java.name");
        hashMap.put("datacard_prepaid", name4);
        String name5 = AJRRechargeActivity.class.getName();
        k.a((Object) name5, "AJRRechargeActivity::class.java.name");
        hashMap.put("datacard_postpaid", name5);
        String name6 = AJRRechargeActivity.class.getName();
        k.a((Object) name6, "AJRRechargeActivity::class.java.name");
        hashMap.put("mobile-prepaid", name6);
        String name7 = AJRRechargeActivity.class.getName();
        k.a((Object) name7, "AJRRechargeActivity::class.java.name");
        hashMap.put("mobile-postpaid", name7);
        String name8 = AJRRechargeActivity.class.getName();
        k.a((Object) name8, "AJRRechargeActivity::class.java.name");
        hashMap.put("datacard-prepaid", name8);
        String name9 = AJRRechargeActivity.class.getName();
        k.a((Object) name9, "AJRRechargeActivity::class.java.name");
        hashMap.put("datacard-postpaid", name9);
        String name10 = AJRRechargeUtilityActivity.class.getName();
        k.a((Object) name10, "AJRRechargeUtilityActivity::class.java.name");
        hashMap.put("dth", name10);
        String name11 = AJRRechargeUtilityActivity.class.getName();
        k.a((Object) name11, "AJRRechargeUtilityActivity::class.java.name");
        hashMap.put("DTH", name11);
        String name12 = AJRRechargeActivity.class.getName();
        k.a((Object) name12, "AJRRechargeActivity::class.java.name");
        hashMap.put("tollcard", name12);
        String name13 = AJREmbedWebView.class.getName();
        k.a((Object) name13, "AJREmbedWebView::class.java.getName()");
        hashMap.put(CLPConstants.URL_TYPE_EMBED, name13);
        String name14 = AJREmbedWebView.class.getName();
        k.a((Object) name14, "AJREmbedWebView::class.java.getName()");
        hashMap.put("ae_embed", name14);
        String name15 = AJRWebViewActivity.class.getName();
        k.a((Object) name15, "AJRWebViewActivity::class.java.getName()");
        hashMap.put("embed-mall", name15);
        hashMap.put("external", "");
        String name16 = AJRRechargeActivity.class.getName();
        k.a((Object) name16, "AJRRechargeActivity::class.java.name");
        hashMap.put("recharges", name16);
        Class<AJRMainActivity> cls = AJRMainActivity.class;
        k.a((Object) cls, "CJRCSTUtils.getTargetUpdatesActivity()");
        String name17 = cls.getName();
        k.a((Object) name17, "CJRCSTUtils.getTargetUpdatesActivity().name");
        hashMap.put("updates", name17);
        String name18 = AJROrderSummaryActivity.class.getName();
        k.a((Object) name18, "AJROrderSummaryActivity::class.java.name");
        hashMap.put("order_summary", name18);
        k.a((Object) "net.one97.paytm.o2o.movies.activity.AJRMovieOrderSummary", "O2OUtils.getMoviesOrderSummaryPageName()");
        hashMap.put("movie_order_summary", "net.one97.paytm.o2o.movies.activity.AJRMovieOrderSummary");
        k.a((Object) "net.one97.paytm.o2o.amusementpark.activity.AmParkOrderSummary", "O2OUtils.getAPOrderSummaryPageName()");
        hashMap.put("ap_order_summary", "net.one97.paytm.o2o.amusementpark.activity.AmParkOrderSummary");
        k.a((Object) "net.one97.paytm.o2o.events.activity.EventOrderSummary", "O2OUtils.getEventOrderSummaryPageName()");
        hashMap.put("event_order_summary", "net.one97.paytm.o2o.events.activity.EventOrderSummary");
        String name19 = AJRQRActivity.class.getName();
        k.a((Object) name19, "AJRQRActivity::class.java.name");
        hashMap.put("scan_pay", name19);
        String name20 = PaySendActivityV2.class.getName();
        k.a((Object) name20, "PaySendActivityV2::class.java.name");
        hashMap.put(UpiConstants.URL_TYPE_CASH_WALLET, name20);
        String name21 = LoanLeadActivity.class.getName();
        k.a((Object) name21, "LoanLeadUtils.getLoanLeadName()");
        hashMap.put("loan", name21);
        String name22 = AJRRechargeUtilityActivity.class.getName();
        k.a((Object) name22, "AJRRechargeUtilityActivity::class.java.name");
        hashMap.put("challan", name22);
        String name23 = AJRMainActivity.class.getName();
        k.a((Object) name23, "AJRMainActivity::class.java.name");
        hashMap.put(Utility.VERTICAL_NAME_MALL, name23);
        hashMap.put("goldweex", "net.one97.paytm.finance.FinanceInitActivity");
        hashMap.put("gold-sip", "net.one97.paytm.finance.FinanceInitActivity");
        hashMap.put("gold-passbook", "net.one97.paytm.finance.FinanceInitActivity");
        hashMap.put("gold-gift", "net.one97.paytm.finance.FinanceInitActivity");
        hashMap.put("digital-gold", "net.one97.paytm.finance.FinanceInitActivity");
        hashMap.put("paytm-postpaid", "net.one97.paytm.finance.FinanceInitActivity");
        String n = ba.n();
        k.a((Object) n, "TravelUtils.getAJRWeexActivity()");
        hashMap.put("weexurl", n);
        String name24 = AJRSavedPaymentActivity.class.getName();
        k.a((Object) name24, "AJRSavedPaymentActivity::class.java.name");
        hashMap.put("saved_card", name24);
        String name25 = AJRSavedPaymentActivity.class.getName();
        k.a((Object) name25, "AJRSavedPaymentActivity::class.java.name");
        hashMap.put("add_card", name25);
        String name26 = AJRProfileActivity.class.getName();
        k.a((Object) name26, "AJRProfileActivity::class.java.name");
        hashMap.put("profile", name26);
        String name27 = AJRRechargeUtilityActivity.class.getName();
        k.a((Object) name27, "AJRRechargeUtilityActivity::class.java.name");
        hashMap.put("utility", name27);
        String name28 = AJRRechargeUtilityActivity.class.getName();
        k.a((Object) name28, "AJRRechargeUtilityActivity::class.java.name");
        hashMap.put("utility_creditcard", name28);
        String name29 = AJRAutomaticSubscriptionListActivity.class.getName();
        k.a((Object) name29, "AJRAutomaticSubscription…Activity::class.java.name");
        hashMap.put("automatic", name29);
        String name30 = AJRMainActivity.class.getName();
        k.a((Object) name30, "AJRMainActivity::class.java.name");
        hashMap.put("homepage_primary", name30);
        String name31 = AJRMainActivity.class.getName();
        k.a((Object) name31, "AJRMainActivity::class.java.name");
        hashMap.put("open", name31);
        k.a((Object) "net.one97.paytm.o2o.movies.activity.MoviesHomeActivity", "O2OUtils.getMoviesHomePageName()");
        hashMap.put("movietickets", "net.one97.paytm.o2o.movies.activity.MoviesHomeActivity");
        k.a((Object) "net.one97.paytm.o2o.movies.activity.MoviesHomeActivity", "O2OUtils.getMoviesHomePageName()");
        hashMap.put("moviepass", "net.one97.paytm.o2o.movies.activity.MoviesHomeActivity");
        k.a((Object) "net.one97.paytm.o2o.movies.activity.AJRIMAXCinemasPage", "O2OUtils.getIMAXPageName()");
        hashMap.put("imaxpage", "net.one97.paytm.o2o.movies.activity.AJRIMAXCinemasPage");
        k.a((Object) "net.one97.paytm.o2o.movies.activity.AJRUpcomingMoviesGridPage", "O2OUtils.getUpcomingMoviesGridPageName()");
        hashMap.put("upcoming-movies", "net.one97.paytm.o2o.movies.activity.AJRUpcomingMoviesGridPage");
        k.a((Object) "net.one97.paytm.o2o.movies.activity.MoviesHomeActivity", "O2OUtils.getMoviesHomePageName()");
        hashMap.put("movies-show-time", "net.one97.paytm.o2o.movies.activity.MoviesHomeActivity");
        k.a((Object) "net.one97.paytm.o2o.movies.activity.MoviesHomeActivity", "O2OUtils.getMoviesHomePageName()");
        hashMap.put("movies_group", "net.one97.paytm.o2o.movies.activity.MoviesHomeActivity");
        k.a((Object) "net.one97.paytm.o2o.movies.activity.MoviesHomeActivity", "O2OUtils.getMoviesHomePageName()");
        hashMap.put("movie-details", "net.one97.paytm.o2o.movies.activity.MoviesHomeActivity");
        k.a((Object) "net.one97.paytm.o2o.movies.activity.MoviesHomeActivity", "O2OUtils.getMoviesHomePageName()");
        hashMap.put("movies-seat-layout", "net.one97.paytm.o2o.movies.activity.MoviesHomeActivity");
        try {
            Class<?> cls2 = Class.forName("net.one97.paytm.cst.cstWidgetization.view.AJRCSTWidgetLanding");
            k.a((Object) cls2, "Class.forName(CSTDeepLin…getCSTLandingCalssName())");
            String name32 = cls2.getName();
            k.a((Object) name32, "Class.forName(CSTDeepLin…TLandingCalssName()).name");
            hashMap.put("contactus", name32);
        } catch (ClassNotFoundException e2) {
            q.b(e2.getMessage());
        }
        k.a((Object) "net.one97.paytm.o2o.events.activity.EventsVerticalActivity", "O2OUtils.getEventsHomePageName()");
        hashMap.put(EventsModuleManager.MODULE_NAME, "net.one97.paytm.o2o.events.activity.EventsVerticalActivity");
        String name33 = AJRAuthActivity.class.getName();
        k.a((Object) name33, "AJRAuthActivity::class.java.name");
        hashMap.put("signin_profile", name33);
        k.a((Object) "net.one97.paytm.o2o.amusementpark.activity.AmParkVerticalActivity", "O2OUtils.getAmParkHomePageName()");
        hashMap.put("amusement", "net.one97.paytm.o2o.amusementpark.activity.AmParkVerticalActivity");
        k.a((Object) "net.one97.paytm.o2o.amusementpark.activity.AmParkVerticalActivity", "O2OUtils.getAmParkHomePageName()");
        hashMap.put("amusement", "net.one97.paytm.o2o.amusementpark.activity.AmParkVerticalActivity");
        k.a((Object) "net.one97.paytm.o2o.movies.activity.AJRPostOrderFoodAndBeverages", "O2OUtils.getFoodAndBeveragesPageName()");
        hashMap.put("postorder_fb", "net.one97.paytm.o2o.movies.activity.AJRPostOrderFoodAndBeverages");
        String name34 = NearByMainActivity.class.getName();
        k.a((Object) name34, "NearByMainActivity::class.java.name");
        hashMap.put("nearby", name34);
        String name35 = P2PActivity.class.getName();
        k.a((Object) name35, "P2PActivity::class.java.name");
        hashMap.put("sendmoneymobile", name35);
        String name36 = ActiveSubscriptionActivity.class.getName();
        k.a((Object) name36, "ActiveSubscriptionActivity::class.java.name");
        hashMap.put("active_subscription", name36);
        String name37 = DeeplinkDeciderActivity.class.getName();
        k.a((Object) name37, "DeeplinkDeciderActivity::class.java.name");
        hashMap.put("manage_beneficiary", name37);
        String name38 = AJRNonKYCDeeplink.class.getName();
        k.a((Object) name38, "AJRNonKYCDeeplink::class.java.name");
        hashMap.put("add_pan", name38);
        String name39 = AJRNonKYCDeeplink.class.getName();
        k.a((Object) name39, "AJRNonKYCDeeplink::class.java.name");
        hashMap.put("add_aadhaar", name39);
        String name40 = MinKycPanAadharUpgradeActivity.class.getName();
        k.a((Object) name40, "MinKycPanAadharUpgradeActivity::class.java.name");
        hashMap.put("min_kyc", name40);
        String name41 = AJRSecuritySettings.class.getName();
        k.a((Object) name41, "AJRSecuritySettings::class.java.name");
        hashMap.put("passcode", name41);
        k.a((Object) "net.one97.paytm.o2o.movies.activity.MoviesHomeActivity", "O2OUtils.getMoviesHomePageName()");
        hashMap.put("freemovie", "net.one97.paytm.o2o.movies.activity.MoviesHomeActivity");
        try {
            Class<?> cls3 = Class.forName("net.one97.paytm.cst.activity.AJRCSTIssueDetail");
            k.a((Object) cls3, "Class.forName(CSTDeepLin…STIssueDetailCalssName())");
            String name42 = cls3.getName();
            k.a((Object) name42, "Class.forName(CSTDeepLin…ueDetailCalssName()).name");
            hashMap.put("cst", name42);
            Class<?> cls4 = Class.forName("net.one97.paytm.cst.activity.AJRCSTOrderIssues");
            k.a((Object) cls4, "Class.forName(CSTDeepLin…CSTOrderIssueCalssName())");
            String name43 = cls4.getName();
            k.a((Object) name43, "Class.forName(CSTDeepLin…derIssueCalssName()).name");
            hashMap.put("csttree", name43);
            Class<?> cls5 = Class.forName("net.one97.paytm.cst.cstWidgetization.view.AJRCSTWidgetLanding");
            k.a((Object) cls5, "Class.forName(CSTDeepLin…getCSTLandingCalssName())");
            String name44 = cls5.getName();
            k.a((Object) name44, "Class.forName(CSTDeepLin…TLandingCalssName()).name");
            hashMap.put(DeepLinkConstant.CIR_CONTACT_US, name44);
        } catch (ClassNotFoundException e3) {
            q.b(e3.getMessage());
        }
        String name45 = AJRYoutubeVideoPlay.class.getName();
        k.a((Object) name45, "O2OUtils.getMoviesYouTubePageName()");
        hashMap.put(H5ResourceHandlerUtil.VIDEO, name45);
        String name46 = UpiPassbookActivity.class.getName();
        k.a((Object) name46, "UpiPassbookActivity::class.java.name");
        hashMap.put("upi_passbook", name46);
        String name47 = UpiLandingPageActivity.class.getName();
        k.a((Object) name47, "UpiLandingPageActivity::class.java.name");
        hashMap.put("upi_landing", name47);
        String name48 = UpiReferralActivity.class.getName();
        k.a((Object) name48, "UpiReferralActivity::class.java.name");
        hashMap.put("upi_referral", name48);
        try {
            Class<?> cls6 = Class.forName("net.one97.paytm.cst.cstWidgetization.view.AJRCSTWidgetLanding");
            k.a((Object) cls6, "Class.forName(CSTDeepLin…getCSTLandingCalssName())");
            String name49 = cls6.getName();
            k.a((Object) name49, "Class.forName(CSTDeepLin…TLandingCalssName()).name");
            hashMap.put(DeepLinkConstant.CIR_CONTACT_US, name49);
        } catch (ClassNotFoundException e4) {
            q.b(e4.getMessage());
        }
        String name50 = UpiAwarenessActivity.class.getName();
        k.a((Object) name50, "UpiAwarenessActivity::class.java.name");
        hashMap.put("upi_awareness", name50);
        String name51 = RequestMoneyV2Activity.class.getName();
        k.a((Object) name51, "RequestMoneyV2Activity::class.java.name");
        hashMap.put("request", name51);
        String name52 = MoneyTransferLinkAccountActivity.class.getName();
        k.a((Object) name52, "MoneyTransferLinkAccountActivity::class.java.name");
        hashMap.put(UpiConstants.FEATURE_TYPE_VIEW_LINKED_BANK_ACCOUNTS, name52);
        String name53 = MoneyTransferLinkAccountActivity.class.getName();
        k.a((Object) name53, "MoneyTransferLinkAccountActivity::class.java.name");
        hashMap.put(UpiConstants.FEATURE_TYPE_LINK_BANK_LIST, name53);
        String name54 = P2PReferShopActivity.class.getName();
        k.a((Object) name54, "P2PReferShopActivity::class.java.name");
        hashMap.put("refer_merchant", name54);
        String name55 = AJRAuthActivity.class.getName();
        k.a((Object) name55, "AJRAuthActivity::class.java.name");
        hashMap.put("login", name55);
        String name56 = AJRQRActivity.class.getName();
        k.a((Object) name56, "AJRQRActivity::class.java.name");
        hashMap.put("link_payment", name56);
        String q = ba.q();
        k.a((Object) q, "TravelUtils.getAJRReferDeepLinkActivityClassName()");
        hashMap.put("referral_travel", q);
        String q2 = ba.q();
        k.a((Object) q2, "TravelUtils.getAJRReferDeepLinkActivityClassName()");
        hashMap.put("travel_buddy", q2);
        String r = ba.r();
        k.a((Object) r, "TravelUtils.getAJRReferHomeActivityClassName()");
        hashMap.put("referral", r);
        Class<AJRMainActivity> cls7 = AJRMainActivity.class;
        k.a((Object) cls7, "CJRCSTUtils.getTargetUpdatesActivity()");
        String name57 = cls7.getName();
        k.a((Object) name57, "CJRCSTUtils.getTargetUpdatesActivity().name");
        hashMap.put("vibe", name57);
        try {
            Class<?> cls8 = Class.forName("net.one97.paytm.landingpage.activity.AJRInboxNewsWebView");
            k.a((Object) cls8, "Class.forName(\"net.one97…ity.AJRInboxNewsWebView\")");
            String name58 = cls8.getName();
            k.a((Object) name58, "Class.forName(\"net.one97…JRInboxNewsWebView\").name");
            hashMap.put("news_details", name58);
        } catch (ClassNotFoundException e5) {
            q.b(e5.getMessage());
        }
        Map<String, String> unmodifiableMap = Collections.unmodifiableMap(hashMap);
        k.a((Object) unmodifiableMap, "Collections.unmodifiableMap(activityMap)");
        f69704b = unmodifiableMap;
    }

    private b() {
    }

    public static Map<String, String> a() {
        return f69704b;
    }
}
